### ISSUE TITLE
Registry location is different on my computer

### ISSUE THREAD

**Issue by myrkron** [CodePenguin/PlayPass#1]
Hi,

I tried to run the release on my computer but got an Undefined error.  So I downloaded VS 2013 Express and saw that it's because the registry location hard-coded in your PlayOnSettings.cs code is not the same as the location in my registry.  I've updated the code to check first your location, then my location.  Now it works on my computer. Here's the file:

using Microsoft.Win32;

namespace PlaySharp
{

    /// <summary>
    /// A static class used to get settings from the locally installed PlayOn instance.
    /// </summary>
    public static class PlayOnSettings
    {
        /// <summary>
        /// The registry key where the PlayOn settings reside.
        /// </summary>
        public const string PlayOnRegistryKey = "Software\\MediaMall\\MediaMall\\CurrentVersion\\Settings";
        public const string PlayOnRegistryKey2 = "Software\\Wow6432Node\\MediaMall\\MediaMall\\CurrentVersion\\Settings";

        /// <summary>
        /// Gets the PlayOn Media Storage Location value from the registry.
        /// </summary>
        public static string GetMediaStorageLocation()
        {
            try
            {
                RegistryKey Reg = Registry.LocalMachine.OpenSubKey(PlayOnRegistryKey);
                foreach (string Item in Reg.GetValue("mediaStoragePaths").ToString().Split('*'))
                    if (System.IO.Directory.Exists(Item))
                        return Item;
            }
            catch
            {
                try
                {
                    RegistryKey Reg = Registry.LocalMachine.OpenSubKey(PlayOnRegistryKey2);
                    foreach (string Item in Reg.GetValue("mediaStoragePaths").ToString().Split('*'))
                        if (System.IO.Directory.Exists(Item))
                            return Item;
                }
                catch
                {

                }
            }
            return "";
        }

        /// <summary>
        /// Gets the PlayOn Video Format value from the registry.
        /// </summary>
        public static string GetPlayLaterVideoFormat()
        {
            try
            {
                RegistryKey Reg = Registry.LocalMachine.OpenSubKey(PlayOnRegistryKey);
                if (Reg.GetValue("playLaterVideoFormat", 0).ToString() == "1")
                    return ".plv";
                else
                    return ".mp4";
            }
            catch
            {
                try
                {
                    RegistryKey Reg = Registry.LocalMachine.OpenSubKey(PlayOnRegistryKey2);
                    if (Reg.GetValue("playLaterVideoFormat", 0).ToString() == "1")
                        return ".plv";
                    else
                        return ".mp4";
                }
                catch
                {
                }
            }
            return ".mp4";
        }
    }

}

**Comment by CodePenguin** [comment]
As of Version 1.0.3 64-bit windows is now supported.
