### ISSUE TITLE
queue and scan matching should be case insensitive

### ISSUE THREAD

**Issue by bj80422** [CodePenguin/PlayPass#2]
This helps with matching on plugins where it seems a little less predictable.

    diff --git a/PlaySharp/Util.cs b/PlaySharp/Util.cs
    index 79d5e5d..4b810b0 100644
    --- a/PlaySharp/Util.cs
    +++ b/PlaySharp/Util.cs
    @@ -69,7 +69,7 @@ namespace PlaySharp
             /// <returns></returns>
             public static bool MatchesPattern(string Value, string Pattern)
             {
    -            return new Regex("^" + Regex.Escape(Pattern).Replace(@"\*", ".*").R
    +            return new Regex("(?i)^" + Regex.Escape(Pattern).Replace(@"\*", ".*
             }
         }

**Comment by CodePenguin** [comment]
Matching in Version 1.0.4 is now case insensitive.
