### ISSUE TITLE
Examples of Amazon pass?

### ISSUE THREAD

**Issue by samgreco** [CodePenguin/PlayPass#3]
I have add the following to the cfg file:

		<pass enabled="1" description="Amazon Queue">
			<scan name="Amazon Instant Video" />
			<scan name="Prime Watchlist" />
			<scan name="TV Shows" />
			<queue name="*" />
		</pass>

And it is not finding anything.  The Hulu queue works well.  Anything obvious?

**Comment by CodePenguin** [comment]
Have you used verbose mode from the command line?  This will give you a lot of details of what it is trying to match against.

`Playpass.exe -verbose`

I don't have Amazon Instant Video setup at the moment.

**Comment by samgreco** [comment]
Yup.  It just tells me that no matches are found even though I have a bunch of stuff in the Amazon queue.  Shows Checking and Scanning of each segment but finds nothing.  SageTV sees the whole queue.

**Comment by samgreco** [comment]
Found it.  Amazon breaks it down by season.  So there is another layer.  So for anyone else trying this, this is what works:

		<pass enabled="1" description="Amazon Queue">
			<scan name="Amazon Instant Video" />
			<scan name="Prime Watchlist" />
			<scan name="TV Shows" />
			<scan name="*" />
			<queue name="*" />
		</pass>

**Comment by CodePenguin** [comment]
That makes sense.  `scan` is for folders and `queue` is for videos.  So it was trying to `queue` folders which would be ignored because they aren't queue-able.  Glad you got it working.

**Comment by CodePenguin** [comment]
I've added this example to the [Wiki: Example Passes](https://github.com/CodePenguin/PlayPass/wiki/Example-Passes#amazon-instant-video-watchlist)

**Comment by samgreco** [comment]
Actually, this may still be an issue.  It stops at the first season it finds.  In this case it list the 4 seasons of this series backwards.  So it finds all of the episodes of Season 4 and stops.  Any way to get it to continue?

**Comment by CodePenguin** [comment]
This is actually by design at the moment.  The `scan` processor is implemented as a single match scanner.  So once it finds a match in the tree, it stops and goes to the next item (`scan` or `queue`) in the list.  I do have plans to re-implement the scanner as a recursive multi-match scanner in the near future.  You can open a new issue as a wishlist item if you'd like.  Either way it is on my list.

**Comment by myrkron** [comment]
It seems to you me that you want to record all of the episodes from all of the seasons, and to do that is simple. Just add more pass tags. You can add as many as you like, so that you can provide the specific path to each show.  Like this (please note that I don't know the proper search phrases, so I'm giving examples):
    <pass enabled="1" description="Amazon Queue 1">
        <scan name="Amazon Instant Video" />
        <scan name="Prime Watchlist" />
        <scan name="TV Shows" />
        <scan name="Season 1" />
        <queue name="*" />
    </pass>

    <pass enabled="1" description="Amazon Queue 2">
        <scan name="Amazon Instant Video" />
        <scan name="Prime Watchlist" />
        <scan name="TV Shows" />
        <scan name="Season 2" />
        <queue name="*" />
    </pass>

    <pass enabled="1" description="Amazon Queue 3">
        <scan name="Amazon Instant Video" />
        <scan name="Prime Watchlist" />
        <scan name="TV Shows" />
        <scan name="Season 3" />
        <queue name="*" />
    </pass>

    <pass enabled="1" description="Amazon Queue 4">
        <scan name="Amazon Instant Video" />
        <scan name="Prime Watchlist" />
        <scan name="TV Shows" />
        <scan name="Season 4" />
        <queue name="*" />
    </pass>

**Comment by CodePenguin** [comment]
@myrkron, that is definitely the way to do it right now.  The new scanner will allow more flexibility so that you can do a lot more with one `pass`.

**Comment by CodePenguin** [comment]
[Version 1.1.0](https://github.com/CodePenguin/PlayPass/releases/tag/v1.1.0) has just been released and includes the new redesigned scanner that can do multiple seasons or shows in one pass.
