### ISSUE TITLE
"Only record after.."

### ISSUE THREAD

**Issue by mobamoba** [CodePenguin/PlayPass#4]
This is more of a question than an issue per se. Is there a way to tell PlayPass to ignore all shows prior to a certain date or a certain season/episode combo? For example, if I'm already in season 6 of a show prior to using PlayPass - and prior to using PlayLater - it would be nice to be able to tell PlayPass to only record "from Season 6 Episode 11 onward" or "only shows with airdates after March 15, 2015" or somesuch. Is there a way to do this? Because otherwise the only way I see is to do a lot of manually skipping shows. Thanks.

**Comment by CodePenguin** [comment]
The main problem is that there isn't a standard for how shows indicate what season/series/episode a video is attached to.  Some use a folder for the seasons, some just put all episodes in one folder.  To help out this situation I just added Version 1.1.3 that includes the ability to add an `exclude` property to `scan` and `queue` nodes.  

The following example will queue all seasons except 1-3:
```
<scan name="Season *" exclude="Season 1|Season 2|Season 3>  
```
If you want to exclude a portion of a season, add a `pass` that would include that season and then execute PlayPass once using the `-skip` command line parameter to add skip files for that season.  That will skip all current episodes but queue up any new episodes as they come.  If there are certain videos that you still want to queue up, just delete the `FILE.playpass.skip` file for the ones you want to queue.

This seems to be an easy to use solution that can be used in a variety of situations.  Hopefully, this will help in your situation.  I'll continue to think on the complex expressions like airdate requirements and such.  It is an interesting idea but I need to make sure that it doesn't overly complicate the config files.

**Comment by mobamoba** [comment]
I see - that should work. Any chance you might add a GUI to more easily insert shows into the cfg? I'm a new PlayLater user and have, like, 70 shows from various channels to add (the drastic bulk will be skipped on the initial run since I've already seen the past episodes), and it sure would be easier to type them into a GUI and click "add to cfg" because I'm pretty sure I'm going to end up screwing up the number of </scan> for a given recording at some point in this process. :)

**Comment by mobamoba** [comment]
Another question (sorry :)): is there a way to exclude episode patterns? I'm asking because I've noticed that many networks shove clips and interviews into their "Full Episodes" section and label them with the pattern sxxe00, so is there a way to set a pattern exclusion so Playpass can automatically skip anything that contains e00? Thanks.

**Comment by CodePenguin** [comment]
You can use the same `exclude` property on a `queue` node to do that.  Here is an example that matches anything like S02E00:
```
<queue name="*" exclude="s*e00*" />
```
