### ISSUE TITLE
Record order

### ISSUE THREAD

**Issue by samgreco** [CodePenguin/PlayPass#6]
Seems like everything is recorded backwards as far as season/episode numbers.  Any way to make it sort ascending rather than descending?  Or is this just the way that Amazon and Hulu present the lists?

**Comment by CodePenguin** [comment]
PlayPass walks through the items in the order that they are presented.  It is up to the channel to determine the order.  For example, the Hulu queue has has multiple ways to sort (Date,Name, Play Order, Show) so PlayPass will walk based on which path you choose.

**Comment by samgreco** [comment]
Figured.  Just wanted to be sure.  Thanks.
