### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by mobamoba** [CodePenguin/PlayPass#7]
I really like your program and still use it even though Playon has a subscription feature (yours is better frankly). However, it doesn't seem to work right with the latest version. It runs fine but doesn't seem to find new shows and add them to the queue? Any way to fix this? Thanks.

**Comment by CodePenguin** [comment]
I just verified that I was running the latest version of PlayOn and the PlayPass queuing system worked fine for my config set (Hulu Queue and various ABC, NBC, CBS shows on their respective sites).  It is possible that the specific channel that you are queuing may have changed the folder structure so your config might need to be updated.  Execute PlayPass with the `-verbose` command line parameter and that should help you see if the matching is failing.

**Comment by mobamoba** [comment]
User error! :) I moved Playpass to a different drive and forgot to update the config.
