### ISSUE TITLE
Request: Add feature to reverse order of operations for scan or queue

### ISSUE THREAD

**Issue by DavidSpivey** [CodePenguin/PlayPass#8]
Thank you so very much for this program. It has filled a need I have had for a very long time.

I often use playpass to queue from services where I have a [VERY] extensive watchlist. However, when queuing videos, the order playon shows these videos in is newest first, meaning that the last thing I queued is at the top of the list. This presents a little bit of a problem, since as I am constantly adding to the watchlist, the oldest items on my list actually never "rise to the top". I would like a -reverse command line option or an xml property that allows me to queue specific lists in reverse order, from "bottom to top" as it were.

This is especially true where TV shows that are currently running have the most recent video at the top for all seasons. As playon is queuing and recording, it records from the last episode of the season to the first. If I want to watch as soon as they are recorded, in the order they were aired, I need to add them from the bottom to the top.

Rarely, but sometimes, the seasons themselves are actually in reverse order as well. So I could be recording season 9 without having the slightest clue what happened in season 1 ... you get the point.

**Comment by CodePenguin** [comment]
I just pushed version 1.1.6 that includes the changes to allow the reverse of a scan or queue action.  You just add `reverse="true"` to any scan or queue action in the config file and it will walk through the current folder in reverse.  Below is an example that will go through the Seasons and Episodes in reverse order.  This example assumes that the seasons and episodes are ordered with the most recent ones first:

```xml
<playpass>
    <passes>
        <pass description="Random TV Shows">
            <scan name="Random TV Network">
                <scan name="All Current Shows">
                    <scan name="Random TV Show">
                        <scan name="Season *" reverse="true">
                            <queue name="*" reverse="true"/>
                        </scan>
                    </scan>
                </scan>
            </scan>
        </pass>
    </passes>
</playpass>
```

**Comment by DavidSpivey** [comment]
Awesome! I tell you, having a responsive developer like yourself is a real pleasure. I appreciate this very much.
