### ISSUE TITLE
Skip File Location

### ISSUE THREAD

**Issue by jtshiv** [CodePenguin/PlayPass#9]
In the readme it says that they're saved in the playlater location by default. Is there a setting where we can define a new location for these files?

Thanks!

**Comment by CodePenguin** [comment]
You are in luck!  The [Advanced Settings wiki](https://github.com/CodePenguin/PlayPass/wiki/Advanced-Settings#queue-lists-and-skip-files) has a section that mentions how to setup a new `queuelist` provider with a custom location.  Here is what I have running in my own config that stores the skip files in a separate folder located at `D:\videos\SkipFiles`:
```xml
<playpass>
	<settings>
		<queuelist settings="Provider=FileQueueList;Data Source=D:\videos\SkipFiles" />
	</settings>
	<passes>
	...
	</passes>
</playpass>
```
